class EroriValidare(Exception):
    pass

class RepoError(Exception):
    pass